name: Build and deploy this application

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: run test
        run: mvn -B test --file pom.xml
      - name: build application
        run: mvn -B clean package --file pom.xml